# Begin Project
project:
  type: tutorial-template
  render:
    - "*.qmd"
    - "!hallgren-2013/"
    - "!ihle-2020/"
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/Introduction-Simulations-in-R
website:
  title: "Introduction to Simulations in R"
  page-footer:
    border: false
    center: © 2024 Malika Ihle. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/Introduction-Simulations-in-R

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/Introduction-Simulations-in-R
          - text: Report a Bug
            href: https://github.com/lmu-osc/Introduction-Simulations-in-R/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: docked
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Tutorial"
        contents:
          - href: tutorial-pages/download-repo.qmd
            text: Download the material
          - href: tutorial-pages/definition.qmd
            text: Definition
          - href: tutorial-pages/purpose.qmd
            text: Purpose
          - href: tutorial-pages/basic-principles.qmd
            text: Basic principles
          - href: tutorial-pages/random-numbers-generators.qmd
            text: Random number generators
          - href: tutorial-pages/repeat.qmd
            text: Repeat
          - href: tutorial-pages/seed.qmd
            text: Setting the seed
          - href: tutorial-pages/sample-size-n.qmd
            text: Sample size `n`
          - href: tutorial-pages/number-of-simulations-nrep.qmd
            text: Number of repetitions `nrep`
          - href: tutorial-pages/dry-rule.qmd
            text: DRY rule
          - href: tutorial-pages/check-alpha.qmd
            text: Simulate to check alpha
          - href: tutorial-pages/check-power.qmd
            text: Simulate to check power
          - href: tutorial-pages/simulate-for-preregistration.qmd
            text: Simulate to prepare a preregistration
          - href: tutorial-pages/general-structure.qmd
            text: General structure
          - href: tutorial-pages/limitations.qmd
            text: Limitations
          - href: tutorial-pages/real-life-example.qmd
            text: Real-life example
          - href: tutorial-pages/resources.qmd
            text: Additional resources
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
include-after-body:
  - file: footer/footer.html
# End Includes

# Begin Format
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
