project:
  type: website
  render:
    - "*.qmd"
    - "!Hallgreen2013/"
    - "!Ihle2020/"

website:
  title: "Introduction to Simulations in R"
  page-footer:
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/Introduction-Simulations-in-R
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/LMU-OSC_favicon.jpg
  margin-header: |
    ![](/assets/LMU-OSC_logo.jpg){width="175"}

  sidebar:
    style: docked
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Tutorial"
        contents:
          - href: ./tutorial_pages/download-repo.qmd
            text: Download the material
          - href: ./tutorial_pages/definition.qmd
            text: Definition
          - href: ./tutorial_pages/purpose.qmd
            text: Purpose
          - href: ./tutorial_pages/basic-principles.qmd
            text: Basic principles
          - href: ./tutorial_pages/random-numbers-generators.qmd
            text: Random number generators
          - href: ./tutorial_pages/repeat.qmd
            text: Repeat
          - href: ./tutorial_pages/seed.qmd
            text: Setting the seed
          - href: ./tutorial_pages/sample-size-n.qmd
            text: Sample size `n`
          - href: ./tutorial_pages/number-of-simulations-nrep.qmd
            text: Number of repetitions `nrep`
          - href: ./tutorial_pages/dry-rule.qmd
            text: DRY rule
          - href: ./tutorial_pages/check-alpha.qmd
            text: Simulate to check alpha
          - href: ./tutorial_pages/check-power.qmd
            text: Simulate to check power
          - href: ./tutorial_pages/simulate-for-preregistration.qmd
            text: Simulate to prepare a preregistration
          - href: ./tutorial_pages/general-structure.qmd
            text: General structure
          - href: ./tutorial_pages/limitations.qmd
            text: Limitations
          - href: ./tutorial_pages/real-life-example.qmd
            text: Real-life example
          - href: ./tutorial_pages/resources.qmd
            text: Additional resources

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    include-in-header:
      - file: matomo-analytics.html



